package com.expenseflow.api.dto;

import jakarta.validation.constraints.*;
import lombok.Data;
import java.math.BigDecimal;

/**
 * Data Transfer Object for receiving data to create a new subscription.
 * It doesn't contain fields like 'id' which are generated by the server.
 */
@Data
public class CreateSubscriptionRequest {

    @NotBlank(message = "Subscription name cannot be empty.")
    @Size(min = 2, max = 100)
    private String name;

    @NotNull(message = "Amount cannot be null.")
    @Positive(message = "Amount must be positive.")
    private BigDecimal amount;

    @NotNull
    @Min(1)
    @Max(31)
    private int paymentDay;

    @NotBlank
    private String category;
}